application: hfwwg
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: hfwwg.app

libraries:
- name: django
  version: "latest"

builtins:
- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'



